### ISSUE TITLE
Cannot match any vendor-es2015.js:43427

### ISSUE THREAD

**Issue by vidhathriavadhanyms** [IBM/virtual-mirror-for-ecommerce#15]
I have deployed this application on my phone, but once I enter a name, age, and gender and submit, it says "MobileFirst Foundation unable to authorize COS" after this the recommendations are not getting loaded. Another alert message which says "Virtual Mirror not configured" also appears.
What could have gone wrong?

**Comment by RahulReddyRavipally** [comment]
Hi @vidhathriavadhanyms , the error you sent, it seems like you have not configured the adapter properly on Mobile Foundation.

Please follow the troubleshooting guide ( https://github.com/IBM/virtual-mirror-for-ecommerce/blob/master/TROUBLESHOOTING.md) , connect your phone to your laptop, turn on usb debugging on your phone, open the troubleshooter in chrome and you will know what is the problem

I will recommend you to take a look at the troubleshooting guide : https://github.com/IBM/virtual-mirror-for-ecommerce/blob/master/TROUBLESHOOTING.md

We have updated the documentation few days ago, you might have missed out some steps. Make sure you follow the documentation and perform all the steps from 1 to 4. We have tested and validated entire pattern. It works fine.

Thank you

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms  please follow this guide <https://github.com/IBM/virtual-mirror-for-ecommerce#troubleshooting>. you will come to know where you have gone wrong with the help of debug messages.

**Comment by vidhathriavadhanyms** [comment]
Hi @RahulReddyRavipally @manojjahgirdar ,
I have followed the documentation correctly and checked the guide too. My adapter has got deployed but the application itself is not deployed. Is there something I am missing on during the deployment?
In the mobile foundation dashboard, it shows only the adapter that is deployed, but not the application

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms you might have forgotten to register the app to Mobile Foundation. You can do so by these simple steps documented in [step 4.5.3](https://github.com/IBM/virtual-mirror-for-ecommerce#453-register-the-virtual-mirror-app-to-mfp-server). Thanks.

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar  it's done, still getting the same error

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms Can you share your debug screen? 

![Debug Screen](https://github.com/IBM/virtual-mirror-for-ecommerce/doc/source/images/DebugAndroidConsole.png)

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms Also did [Step 4.4.3](https://github.com/IBM/virtual-mirror-for-ecommerce#443-test-the-imagefetch-adapter) give you the results as mentioned in the examples?

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar Thanks, I followed the troubleshooting guide and successfully deployed it on my phone. Now, the images of the accessories are not getting loaded and when I click on Tryon, it says "Hang On!!" and doesn't go further. I'm attaching the screenshot of the debug screen along with the console. Could you please check and let me know what the error could be.

Thanks

![debugscreen1](https://user-images.githubusercontent.com/33901465/80570200-053db600-8a18-11ea-9d12-8d618384ac8d.png)

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar any updates?

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms Looks like your mobile application has no issues. Go to <https://cloud.ibm.com/resources> Under Storage Click on __Cloud Object Storage__ and verify if you can see the bucket which you created there has been added with the jewelry images. If you cannot see jewelry images there, follow [step 2.2.1](https://github.com/IBM/virtual-mirror-for-ecommerce#221-upload-images-to-cloud-object-storage) Thanks.

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms Also make sure you have done [step 4.4.2](https://github.com/IBM/virtual-mirror-for-ecommerce#442-launch-mfp-dashboard-and-update-adapter-configurations) right, because by configuring adapter with apikey, bucket name, etc you are establishing a secure connection between your mobile app and the Cloud Object Storage where you have stored the Images. Thanks

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar It's done, adapter and the application are correctly deployed. Here I share my Mobile Foundation service dashboard and the debug screen


![DebugScreen2](https://user-images.githubusercontent.com/33901465/81188865-85918780-8fd3-11ea-8c96-5a64ee54ac11.png)


![MobileFoundation](https://user-images.githubusercontent.com/33901465/81188755-5bd86080-8fd3-11ea-956b-034b761e204d.png)

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar I found that in all the image links, the localhost is getting added due to which we may be getting this 404 error. If I copy the same link and remove the localhost from it, I can see the images.

The following are the warnings I'm getting as soon as I open the application
![DebugScreen4](https://user-images.githubusercontent.com/33901465/81293311-bb457780-908a-11ea-965a-42d7c8fa5e4d.png)


This is the error I'm getting
![DebugScreen5](https://user-images.githubusercontent.com/33901465/81293406-ed56d980-908a-11ea-9f84-a90ed2494a05.png)


If I copy the link in the above screenshot and remove the localhost from that, I can see the images
![Hanging](https://user-images.githubusercontent.com/33901465/81293550-242cef80-908b-11ea-89df-e357f0ff2ef5.png)

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms Interesting... I can see that you have configured the Adapter and Deployed the recommendation engine correctly. I don't see from where the `http://localhost/` is getting appended from. I guess there is some issue with the `JewelleryStoreApp`. I'll figure it out and notify you once I fix the application.

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar Sure, Thank you :)

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar I found that in JewelleryStoreApp/e2e/protractor.conf.js, there is a line,
baseUrl: 'http://localhost:4200/'
and in JewelleryStroreApp/MobileFoundationAdapter/ImagesFetch/pom.xml, there is a line,
<mfpfUrl>http://localhost:8080/mfpadmin</mfpfUrl>
Could those be causing a problem?
These are just my findings. There might be many other files in which the URL could be specified.

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar any updates?

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms 

As you explored and found the two occurrences of `http://localhost/` in the source code, the problem is not caused by them. the URL is supposed to be fetched by the application dynamically with the help of Mobile Foundation Adapter. 

For your understanding Image URL is fetched something like this: src=" **(baseURL)(imageName)**". The baseURL is your Cloud Object Storage URL which I can see from the screenshots you sent its __"s3.us.cloud-object-storage.appdomain.cloud/vmbkt/"__ and the imageName are the jewellery product names example __hanging1.png__. Hence the app will display Image with src = "s3.us.cloud-object-storage.appdomain.cloud/vmbkt/hanging1.png".

The problem here is there is no `https://` at the beginning of your baseURL so the final src URL is not a openable URL. 

What you can do is goto your Mobile Foundation Adapter Configuration page and just append `https://` to the `Cloud Object Storage Endpoint Public URL`. and just save the adapter as shown below.

<img width="1680" alt="Screenshot 2020-05-11 at 2 45 26 PM" src="https://user-images.githubusercontent.com/52746337/81545652-ce13c100-9396-11ea-8fdf-a97061a4fca1.png">

After that is done no need to redeploy application or anything.. Open the Application in your Mobile it should show you the Images. 

Hope this fixes the Issue.

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar Thanks a lot, this fixed the issue of localhost. I am able to see the images. 
Now when I click on "Try on Virtual Mirror", it just says "Hang on" and throws an error on the console.

Here I share my debug screen.
![DebugScreen6](https://user-images.githubusercontent.com/33901465/81548128-6d868300-939a-11ea-8815-2f5d3578b085.png)

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms, In this case, you might have not deployed the Virtual Mirror correctly. Goto the `Virtual Mirror API URL` on your web browser it should display an `O.K.` message which indicates the virtual mirror is deployed correctly. If you see "Hello World Starter App" then you have not deployed virtual mirror, follow [step 3](https://github.com/IBM/virtual-mirror-for-ecommerce#3-virtual-mirror-setup) to deploy the application correctly. Thanks.

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar Thanks for the suggestion. I was getting the "Hello world starter app". Hence, I redeployed the Virtual Mirror. Now I am getting an [O.K.](URL) message. I have updated the adapter configuration as well. I redeployed the application on my phone, but I am still getting the same error.

Virtual Mirror API
![VirtuallMirrorApi](https://user-images.githubusercontent.com/33901465/81574211-26f94e80-93c3-11ea-9798-a9dc2398e7b1.png)

Debug Screen
![DebugScreen7](https://user-images.githubusercontent.com/33901465/81574329-4abc9480-93c3-11ea-9d99-2592e78b343e.png)

Thanks

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms I have fixed the application, please clone the `JewelleryStoreApp` directory and don't deploy the adapter again. Just register the application [Step 4.5.3](https://github.com/IBM/virtual-mirror-for-ecommerce#453-register-the-virtual-mirror-app-to-mfp-server) and run the application [Step 4.5.4](https://github.com/IBM/virtual-mirror-for-ecommerce/blob/master/README.md#454-buildrun-the-ionic-application-on-android-phone)

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar Thanks for the response. As suggested, I cloned the JewelleryStroeApp directory and registered the app again. I built it and deployed it on my phone.
I am still getting the same error. There is no change in the path resolution in the error message.

![DebugScreen9](https://user-images.githubusercontent.com/33901465/81658214-307fc680-9456-11ea-8af2-f83836a8a506.png)

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms Are your `Recommendation API URL` and `Virtual Mirror API URL` in this format `https://appname.xx-xx.appdomain.cloud/`? If so remove the `/` from the end of the URL's example: `https://appname.xx-xx.appdomain.cloud` from Mobile Foundation Adapter Configuration page and save the adapter. No need to redeploy the application just open the application on your phone it should fix the error. Thanks.

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar Thanks a lot for your help. The virtual mirror started working, but I'm getting an error when I scroll horizontally, an error appears on the console which says, "[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted."

When I click on "Try on Virtual Mirror", another error which says, "GET https://virtualmirror.eu-gb.cf.appdomain.cloud/images/index.jpg 404 (Not Found)" appears and then it goes further to the virtual mirror. 
![DebugScreen8](https://user-images.githubusercontent.com/33901465/81693251-4654b200-947d-11ea-8869-de2476f51a90.png)

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms The virtual mirror is not appearing ?

**Comment by vidhathriavadhanyms** [comment]
@manojjahgirdar virtual mirror is appearing after this.
But at that point, 404 not found is thrown on the console

**Comment by manojjahgirdar** [comment]
@vidhathriavadhanyms  Since virtual mirror is working you can ignore the error...
